### ISSUE TITLE
Connection test not suitable for chinese users.

### ISSUE THREAD

**Issue by eebssk1** [Magisk-Modules-Repo/ccbins#1]
Although dns request will handle by VPNs,the ping still won't go through VPNs(some just ignore them).So the test will always fail for chinese users.

**Comment by eebssk1** [comment]
Try other test urls

**Comment by Zackptg5** [comment]
That's part of the mod-util file which is @veez21 mod-util template. You'll want to bring this up in his repo here: https://github.com/veez21/mod-util
