### ISSUE TITLE
changing default shell to zsh?

### ISSUE THREAD

**Issue by dxcvvxd** [Magisk-Modules-Repo/ccbins#10]
theres no `chsh` command on android by default. how can i switch from bash to zsh?

**Comment by Zackptg5** [comment]
Just call the binary. So when in terminal, just type the bash or zsh command to open that shell after it's installed. You don't want to change the default shell in android, lots of built-in scripts and parts of the OS expected the default mksh shell and changing that could bork the system

**Comment by dxcvvxd** [comment]
yeah, i guess youre right
i just wanted it to be zsh by default

**Comment by DerGoogler** [comment]
@dxcvvxd, You can install [Systemless Mkshrc](https://github.com/Magisk-Modules-Alt-Repo/mkshrc), after you installed it you should run `su` in any terminal to init. the file tree that this modules creates (default is `/data/mkuser`).

You can run `/system/bin/sh` in Termux (not as a root user) to make a user for Termux. After that you'll find the `/data/mkuser/home/<user-id>/.mkshrc` file (`.bashrc` is just a link). In this file can you configure anything for Termux


`/data/mkuser/home/<user-id>/.mkshrc`
```shell
# Aliases
alias bsu='su -p -s bash'
alias ls='ls --color=auto'
alias lsa='ls --color=auto -A'
alias nano='nano -l'
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

echo "Entering as shell"
su --login shell # or just use your zsh bin
``` 

> If you want put additional binaries then can you put these in `$PREFIX/bin` or `$HOME/.local/bin`
