### ISSUE TITLE
[Feature Request] Add SSH

### ISSUE THREAD

**Issue by diabl0w** [Magisk-Modules-Repo/ccbins#12]
I am not sure if people use rsync for local syncing, but I am used to using it to sync to remote server. This is a feature request to add ssh the the list of binaries. currently, running rsync as 
```
rsync --update --delete -a  /data/media/0/backup/ user@remote.server:/backup
```
results in:
```
rsync: [sender] Failed to exec ssh: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.2.7]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at io.c(231) [sender=3.2.7]
```

**Comment by Zackptg5** [comment]
So I tried openssh once a few months ago and ended up abandoning it cause it turned into dependency hell. I have no plans on adding it any time soon but potentially will give it another whirl at some point (won't be for at least several months).
I'll leave this open so it stays on my radar
