### ISSUE TITLE
Bash Segmentation Fault With Substitution

### ISSUE THREAD

**Issue by jacko9000** [Magisk-Modules-Repo/ccbins#3]
Hi,

The version of bash, 5.1.4(1), gives a segmentation fault on substitution.

For example, given:

FILE="example.tar.gz"

then:

echo "${FILE%.*}"

should display:

example.tar

but, instead, a segmentation fault occurs.

So, instead, I have had to install the Bash for Android Magisk module, which is bash version 5.0.7, where the above example works fine.

Best regards,
Jacko

**Comment by jacko9000** [comment]
Hi,

The version of bash, 5.1.4(1), gives a segmentation fault on string substitution.

For example, given:

FILE="example.tar.gz"

then:

echo "${FILE%.*}"

should display:

example.tar

but, instead, a segmentation fault occurs.

So, instead, I have had to install the Bash for Android Magisk module, which is bash version 5.0.7, where the above example works fine.

Best regards,
Jacko

**Comment by Zackptg5** [comment]
Which arch is your phone? arm64?

**Comment by jacko9000** [comment]
Hi,

Thanks for the prompt response.

Yes, I'm using an arm64 device.

Best regards,
Jacko

**Comment by Zackptg5** [comment]
Looks like it's an actual bash bug and was patched yesterday. I'll have an update out today :)

**Comment by Zackptg5** [comment]
Fix pushed

**Comment by jacko9000** [comment]
Hi,

Thanks for the updated bash.

Just tested it on my device and it works great.

Best regards,
Jacko
