### ISSUE TITLE
Instalation ccbins failed

### ISSUE THREAD

**Issue by atimofeev86** [Magisk-Modules-Repo/ccbins#4]
When I tried install ccbins from magisk I got errror:
Testion internet connection
Unable to download files!
!Instalation failed

internet works on smartphone. I tried over Lte internet and wifi.

**Comment by Zackptg5** [comment]
Can you save the log from the install attempt and post it?

**Comment by atimofeev86** [comment]
[magisk_install_log_2021-06-09T08_22_52Z.log](https://github.com/Magisk-Modules-Repo/ccbins/files/6621288/magisk_install_log_2021-06-09T08_22_52Z.log)

**Comment by atimofeev86** [comment]
@Zackptg5,
Thank you. it works now

**Comment by atimofeev86** [comment]
@Zackptg5,
sorry. it doesn't work

**Comment by Zackptg5** [comment]
[ccbins_v7.3.zip](https://github.com/Magisk-Modules-Repo/ccbins/files/6650108/ccbins_v7.3.zip)
@atimofeev86 
Can you try this zip and post the log like before?

**Comment by atimofeev86** [comment]
log
[magisk_install_log_2021-06-17T23_18_57Z.log](https://github.com/Magisk-Modules-Repo/ccbins/files/6672992/magisk_install_log_2021-06-17T23_18_57Z.log)

**Comment by Zackptg5** [comment]
Are you behind a firewall or in a country that has one?

**Comment by atimofeev86** [comment]
> Are you behind a firewall or in a country that has one?

No, I don't have firewall. I tried several internet connections

**Comment by Zackptg5** [comment]
I'm unable to replicate this issue so it's likely something with your device or your connection. Some countries, isps, and/or cell services have been known to poison dns which could trigger this error or it could be something else entirely. Sorry :/
