### ISSUE TITLE
[feature request] ffmpeg (included)

### ISSUE THREAD

**Issue by eladkarako** [Magisk-Modules-Repo/ccbins#7]
get latest apk from:  
https://github.com/WritingMinds/ffmpeg-android-java/releases/latest/download/app-debug.apk  

or manually, for example:  
https://github.com/WritingMinds/ffmpeg-android-java/releases/download/v0.3.2/app-debug.apk  

unzip the APK to get the assets.
copy `x86/ffmpeg` and `armeabi-v7a/ffmpeg`.

done.

https://github.com/WritingMinds/ffmpeg-android-java also has compilation feature if you want to do it yourself.

if possible, do a non-free version of ffmpeg, with x265 and AV1.

please include x86 compatible binaries for the sake of us using Android-x86 on virtual machine that needs that variation (or maybe create a fork of this repo for that sake only).
[ffmpeg__armeabi-v7a.zip](https://github.com/Magisk-Modules-Repo/ccbins/files/8762523/ffmpeg__armeabi-v7a.zip)
[ffmpeg__x86.zip](https://github.com/Magisk-Modules-Repo/ccbins/files/8762524/ffmpeg__x86.zip)

**Comment by Zackptg5** [comment]
Moving this to the cross compiled binary repo
